# -*- coding: utf-8 -*-
"""HelmetDetection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_YxAX3StfaGpNjDUVht00qJ3H6Al66XZ

## Google Colab Notebook Code

### 1. Setup Environment and Verify GPU
Installs Ultralytics (YOLOv8), ONNX exporter, and dependencies.
"""

!pip install ultralytics onnx onnxruntime opencv-python-headless matplotlib pillow

import torch
import os
from google.colab import files

print("--- ENVIRONMENT CHECK ---")
print(f"PyTorch Version: {torch.__version__}")
if torch.cuda.is_available():
    print(f"GPU Active: {torch.cuda.get_device_name(0)}")
else:
    print("WARNING: GPU not detected. Go to Runtime > Change runtime type > T4 GPU.")

"""### 2. Create Dataset Directory Structure
This cell sets up the directory layout and creates dummy images so the entire notebook is runnable out-of-the-box.
"""

import os
import numpy as np
from PIL import Image

# Define root dataset directory
DATASET_DIR = "/content/selfie_helmet_dataset"
CLASSES = ["full_face_helmet", "half_face_helmet", "no_helmet"]

# Create Train and Validation folders
for split in ["train", "val"]:
    for cls in CLASSES:
        os.makedirs(os.path.join(DATASET_DIR, split, cls), exist_ok=True)

# Generate dummy images so you can test training right now
def generate_dummy_images(folder, count=10):
    for cls in CLASSES:
        target_path = os.path.join(folder, cls)
        for i in range(count):
            # Create a simple colored random image (224x224)
            img_data = np.random.randint(0, 255, (224, 224, 3), dtype=np.uint8)
            img = Image.fromarray(img_data)
            img.save(os.path.join(target_path, f"sample_{i}.jpg"))

generate_dummy_images(os.path.join(DATASET_DIR, "train"), count=20)
generate_dummy_images(os.path.join(DATASET_DIR, "val"), count=5)

print(f"Dataset structure ready at: {DATASET_DIR}")
print("Folders created for: full_face_helmet, half_face_helmet, no_helmet")

"""### 3. Train the YOLO Classification Model
Fine-tunes the lightweight YOLOv8 nano classifier (`yolov8n-cls`) on your selfie classes.
"""

from ultralytics import YOLO

# 1. Load pre-trained weights
model = YOLO('yolov8n-cls.pt')

# 2. Train on your selfie dataset
# Change epochs to 30-50 when training on your actual real images
results = model.train(
    data=DATASET_DIR,
    epochs=5,               # Increase for real dataset
    imgsz=224,              # Standard input resolution for classification
    batch=16,
    project='helmet_project',
    name='selfie_classifier',
    exist_ok=True
)

print("\nTraining completed successfully!")

"""### 4. Verify Inference Logic (True / False Output)
Tests the trained model on an image, applies confidence thresholds, and formats the output into a production JSON response.
"""

import os
import cv2
import matplotlib.pyplot as plt
from ultralytics import YOLO

# Correct path generated by Ultralytics classification trainer
WEIGHTS_PATH = "/content/runs/classify/helmet_project/selfie_classifier/weights/best.pt"

# Fallback to last.pt if best.pt isn't found
if not os.path.exists(WEIGHTS_PATH):
    WEIGHTS_PATH = "/content/runs/classify/helmet_project/selfie_classifier/weights/last.pt"

print(f"Loading model weights from: {WEIGHTS_PATH}")
trained_model = YOLO(WEIGHTS_PATH)

def verify_selfie(image_path, confidence_threshold=0.65):
    # Run classification
    results = trained_model(image_path, verbose=False)

    # Get top prediction class ID and confidence score
    top1_index = results[0].probs.top1
    predicted_class = results[0].names[top1_index]
    confidence = float(results[0].probs.top1conf)

    # Business logic: True if full or half helmet with sufficient confidence
    helmet_worn = (predicted_class in ["full_face_helmet", "half_face_helmet"]) and (confidence >= confidence_threshold)

    return {
        "helmet_worn": helmet_worn,
        "detected_class": predicted_class,
        "confidence": round(confidence, 4)
    }

# Test on a validation sample
test_image_path = "/content/selfie_helmet_dataset/val/full_face_helmet/sample_0.jpg"

response = verify_selfie(test_image_path)

print("\n--- INFERENCE RESULT ---")
print(response)

# Display image
img = cv2.imread(test_image_path)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
plt.title(f"Helmet Worn: {response['helmet_worn']} ({response['detected_class']} - {response['confidence']*100:.1f}%)")
plt.imshow(img)
plt.axis("off")
plt.show()

"""### 5. Export Model for Server Deployment
Exports the trained PyTorch model (`best.pt`) to ONNX format (`best.onnx`) and triggers a file download to your computer.
"""

import os
from ultralytics import YOLO
from google.colab import files

WEIGHTS_PATH = "/content/runs/classify/helmet_project/selfie_classifier/weights/best.pt"

if not os.path.exists(WEIGHTS_PATH):
    WEIGHTS_PATH = "/content/runs/classify/helmet_project/selfie_classifier/weights/last.pt"

export_model = YOLO(WEIGHTS_PATH)

# 1. Export to ONNX format for lightweight server inference
onnx_file_path = export_model.export(format="onnx")
print(f"ONNX Model saved to: {onnx_file_path}")

# 2. Trigger browser downloads for both files
print("Downloading weight files to your computer...")
files.download(WEIGHTS_PATH)
files.download(onnx_file_path)

"""## Production Backend Server Setup (No Retraining Needed)

Once you download `best.pt` or `best.onnx` from Colab, you **never need Colab or training code again**. Place the weight file into your server project directory alongside this deployment script.

### Backend Implementation (`server.py`)

Here is a ready-to-use production server script powered by **FastAPI** that loads your exported model once into memory and handles incoming photo requests instantly:
"""

from fastapi import FastAPI, UploadFile, File, HTTPException
from ultralytics import YOLO
import cv2
import numpy as np

app = FastAPI(title="Selfie Helmet Verification API")

# Load model weights into RAM once when server starts
# Replace "best.pt" with your actual exported file path
MODEL_PATH = "best.pt"
CONFIDENCE_THRESHOLD = 0.70

try:
    model = YOLO(MODEL_PATH)
    print("Selfie Helmet Classifier loaded successfully into server memory.")
except Exception as e:
    raise RuntimeError(f"Failed to load model file: {e}")

@app.post("/verify-helmet")
async def verify_helmet(file: UploadFile = File(...)):
    # Validate file format
    if not file.content_type.startswith("image/"):
        raise HTTPException(status_code=400, detail="File uploaded must be an image.")

    # 1. Convert incoming file stream to OpenCV image array
    contents = await file.read()
    np_array = np.frombuffer(contents, np.uint8)
    img = cv2.imdecode(np_array, cv2.IMREAD_COLOR)

    if img is None:
        raise HTTPException(status_code=400, detail="Invalid or corrupt image data.")

    # 2. Perform Inference
    results = model(img, verbose=False)

    top1_index = results[0].probs.top1
    predicted_class = results[0].names[top1_index]
    confidence = float(results[0].probs.top1conf)

    # 3. Decision Logic
    is_helmet_valid = (
        predicted_class in ["full_face_helmet", "half_face_helmet"]
    ) and (confidence >= CONFIDENCE_THRESHOLD)

    # 4. Return API Response
    return {
        "status": "success",
        "helmet_worn": is_helmet_valid,
        "details": {
            "predicted_class": predicted_class,
            "confidence": round(confidence, 4),
            "threshold_applied": CONFIDENCE_THRESHOLD
        }
    }

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)

"""## How to Run the Server

1. Install dependencies on your server:
```bash
pip install fastapi uvicorn ultralytics opencv-python-headless

```


2. Run the server:
```bash
python server.py

```


3. Send a `POST` request to `http://<your-server-ip>:8000/verify-helmet` with a selfie file in the `file` parameter. The server will respond with:
```json
{
  "status": "success",
  "helmet_worn": true,
  "details": {
    "predicted_class": "full_face_helmet",
    "confidence": 0.9421,
    "threshold_applied": 0.70
  }
}
```
"""