"""add_wallet_balance_to_user

Revision ID: 6b34e1bddbee
Revises: 1c70384e9a27
Create Date: 2026-08-22 22:35:09.992196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b34e1bddbee'
down_revision: Union[str, Sequence[str], None] = '1c70384e9a27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('users', sa.Column('wallet_balance', sa.Float(), nullable=True))
    op.execute("UPDATE users SET wallet_balance = 500.0")
    op.alter_column('users', 'wallet_balance', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'wallet_balance')
    # ### end Alembic commands ###
