import hmac
import hashlib
import logging
from decimal import Decimal, InvalidOperation
from typing import Optional, Dict, Any, Union
import razorpay
from app.core.config import settings

logger = logging.getLogger(__name__)

def get_razorpay_client() -> razorpay.Client:
    return razorpay.Client(auth=(settings.RAZORPAY_KEY_ID, settings.RAZORPAY_KEY_SECRET))

def create_razorpay_order(
    amount_inr: Union[Decimal, float, int],
    receipt: str,
    notes: Optional[Dict[str, Any]] = None
) -> Dict[str, Any]:
    """
    Creates a Razorpay order.
    Amount is converted from INR to paise (smallest currency unit), e.g.
    Rs.5.00 -> 500 paise. Phase 7: the INR->paise conversion is done via
    Decimal, not float multiplication — amount_inr is expected to be the
    Decimal PremiumQuote.final_premium (premium_pricing_service.py)
    converted ONLY here, at the final payment boundary, so no
    binary-float rounding error can creep into what Razorpay actually
    charges. A plain float/int is still accepted (e.g. for a fixed
    ad-hoc amount) and routed through the same Decimal path via str().

    Rejects non-finite (NaN/inf) or unparseable amounts outright — no
    malformed value can reach the Razorpay API from here.
    """
    try:
        amount_decimal = amount_inr if isinstance(amount_inr, Decimal) else Decimal(str(amount_inr))
    except (InvalidOperation, ValueError, TypeError):
        raise ValueError(f"Invalid amount for Razorpay order: {amount_inr!r}")

    if not amount_decimal.is_finite():
        raise ValueError(f"Amount must be a finite number, got: {amount_inr!r}")
    if amount_decimal < 0:
        raise ValueError("Amount must be non-negative")

    amount_paise = int((amount_decimal * 100).to_integral_value(rounding="ROUND_HALF_UP"))
    # Razorpay minimum order amount is ₹1.00 (100 paise)
    if amount_paise < 100:
        amount_paise = 100

    order_payload = {
        "amount": amount_paise,
        "currency": "INR",
        "receipt": receipt,
        "notes": notes or {},
    }

    try:
        client = get_razorpay_client()
        order = client.order.create(data=order_payload)
        logger.info(f"Successfully created Razorpay order: {order.get('id')} for receipt {receipt}")
        return order
    except Exception as e:
        logger.error(f"Failed to create Razorpay order: {str(e)}")
        raise e

def verify_razorpay_signature(
    razorpay_order_id: str,
    razorpay_payment_id: str,
    razorpay_signature: str
) -> bool:
    """
    Verifies the HMAC-SHA256 signature generated by Razorpay Checkout.
    Payload format: f"{razorpay_order_id}|{razorpay_payment_id}"
    Uses constant-time comparison via hmac.compare_digest.
    """
    if not razorpay_order_id or not razorpay_payment_id or not razorpay_signature:
        return False

    try:
        msg = f"{razorpay_order_id}|{razorpay_payment_id}".encode("utf-8")
        secret = settings.RAZORPAY_KEY_SECRET.encode("utf-8")
        generated_signature = hmac.new(secret, msg, hashlib.sha256).hexdigest()

        is_valid = hmac.compare_digest(generated_signature.lower(), razorpay_signature.lower())
        if not is_valid:
            logger.warning(
                f"Razorpay signature mismatch for order {razorpay_order_id}, payment {razorpay_payment_id}"
            )
        return is_valid
    except Exception as e:
        logger.error(f"Error during signature verification: {str(e)}")
        return False

def verify_webhook_signature(
    body_bytes: bytes,
    webhook_signature: str,
    webhook_secret: str
) -> bool:
    """
    Verifies the Razorpay webhook HMAC-SHA256 signature over raw request body.
    """
    if not body_bytes or not webhook_signature or not webhook_secret:
        return False

    try:
        generated_signature = hmac.new(
            webhook_secret.encode("utf-8"),
            body_bytes,
            hashlib.sha256
        ).hexdigest()
        return hmac.compare_digest(generated_signature.lower(), webhook_signature.lower())
    except Exception as e:
        logger.error(f"Error during webhook signature verification: {str(e)}")
        return False
