"""Finalize RideShield database schema

Revision ID: 1c70384e9a27
Revises: 653c1f96e4dd
Create Date: 2026-08-22 12:17:49.200646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c70384e9a27'
down_revision: Union[str, Sequence[str], None] = '653c1f96e4dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_events', sa.Column('entity_type', sa.String(length=50), nullable=False))
    op.add_column('audit_events', sa.Column('entity_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('audit_events_claim_id_fkey'), 'audit_events', type_='foreignkey')
    op.drop_constraint(op.f('audit_events_performed_by_user_id_fkey'), 'audit_events', type_='foreignkey')
    op.create_foreign_key(None, 'audit_events', 'users', ['performed_by_user_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'audit_events', 'claims', ['claim_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('claims_rider_id_fkey'), 'claims', type_='foreignkey')
    op.drop_constraint(op.f('claims_shift_id_fkey'), 'claims', type_='foreignkey')
    op.drop_constraint(op.f('claims_incident_id_fkey'), 'claims', type_='foreignkey')
    op.create_foreign_key(None, 'claims', 'shifts', ['shift_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'claims', 'users', ['rider_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'claims', 'incidents', ['incident_id'], ['id'], ondelete='RESTRICT')
    op.create_check_constraint('ck_claims_approved_amount_non_negative', 'claims', 'approved_amount IS NULL OR approved_amount >= 0')
    op.create_check_constraint('ck_claims_claimed_amount_non_negative', 'claims', 'claimed_amount >= 0')
    op.drop_constraint(op.f('incident_evidence_incident_id_fkey'), 'incident_evidence', type_='foreignkey')
    op.drop_constraint(op.f('incident_evidence_claim_id_fkey'), 'incident_evidence', type_='foreignkey')
    op.create_foreign_key(None, 'incident_evidence', 'claims', ['claim_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'incident_evidence', 'incidents', ['incident_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('incidents_shift_id_fkey'), 'incidents', type_='foreignkey')
    op.drop_constraint(op.f('incidents_rider_id_fkey'), 'incidents', type_='foreignkey')
    op.create_foreign_key(None, 'incidents', 'shifts', ['shift_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'incidents', 'users', ['rider_id'], ['id'], ondelete='RESTRICT')
    op.create_check_constraint('ck_incidents_confidence_score_range', 'incidents', 'confidence_score >= 0 AND confidence_score <= 1')
    op.create_check_constraint('ck_incidents_peak_g_force_non_negative', 'incidents', 'peak_g_force >= 0')
    op.drop_constraint(op.f('payments_rider_id_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'users', ['rider_id'], ['id'], ondelete='RESTRICT')
    op.create_check_constraint('ck_payments_amount_non_negative', 'payments', 'amount >= 0')
    op.create_check_constraint('ck_payments_type_linkage', 'payments', "(payment_type = 'PREMIUM_COLLECTION' AND shift_id IS NOT NULL) OR (payment_type = 'CLAIM_PAYOUT' AND claim_id IS NOT NULL)")
    op.create_check_constraint('ck_rider_profiles_safety_rating_range', 'rider_profiles', 'safety_rating >= 1.00 AND safety_rating <= 5.00')
    op.drop_constraint(op.f('risk_scores_rider_id_fkey'), 'risk_scores', type_='foreignkey')
    op.drop_constraint(op.f('risk_scores_shift_id_fkey'), 'risk_scores', type_='foreignkey')
    op.create_foreign_key(None, 'risk_scores', 'shifts', ['shift_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'risk_scores', 'users', ['rider_id'], ['id'], ondelete='RESTRICT')
    op.create_check_constraint('ck_risk_scores_hard_acceleration_non_negative', 'risk_scores', 'hard_acceleration_count >= 0')
    op.create_check_constraint('ck_risk_scores_hard_braking_non_negative', 'risk_scores', 'hard_braking_count >= 0')
    op.create_check_constraint('ck_risk_scores_overspeeding_non_negative', 'risk_scores', 'overspeeding_count >= 0')
    op.create_check_constraint('ck_risk_scores_score_range', 'risk_scores', 'risk_score >= 0 AND risk_score <= 100')
    op.create_check_constraint('ck_risk_scores_window_end_after_start', 'risk_scores', 'window_end > window_start')
    op.drop_constraint(op.f('shifts_rider_id_fkey'), 'shifts', type_='foreignkey')
    op.create_foreign_key(None, 'shifts', 'users', ['rider_id'], ['id'], ondelete='RESTRICT')
    op.create_check_constraint('ck_shifts_distance_non_negative', 'shifts', 'distance_km >= 0')
    op.create_check_constraint('ck_shifts_end_after_start', 'shifts', 'end_time IS NULL OR end_time >= start_time')
    op.create_check_constraint('ck_shifts_premium_non_negative', 'shifts', 'premium_amount >= 0')
    op.create_index('idx_telemetry_batches_shift_start_timestamp', 'telemetry_batches', ['shift_id', 'start_timestamp'], unique=False)
    op.drop_constraint(op.f('telemetry_batches_shift_id_fkey'), 'telemetry_batches', type_='foreignkey')
    op.create_foreign_key(None, 'telemetry_batches', 'shifts', ['shift_id'], ['id'], ondelete='RESTRICT')
    op.create_check_constraint('ck_telemetry_batches_end_after_start', 'telemetry_batches', 'end_timestamp >= start_timestamp')
    op.create_check_constraint('ck_telemetry_batches_sample_count_positive', 'telemetry_batches', 'sample_count > 0')
    op.create_check_constraint('ck_telemetry_batches_sequence_non_negative', 'telemetry_batches', 'batch_sequence >= 0')
    op.create_check_constraint('ck_telemetry_samples_speed_non_negative', 'telemetry_samples', 'speed >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_telemetry_samples_speed_non_negative', 'telemetry_samples', type_='check')
    op.drop_constraint('ck_telemetry_batches_sequence_non_negative', 'telemetry_batches', type_='check')
    op.drop_constraint('ck_telemetry_batches_sample_count_positive', 'telemetry_batches', type_='check')
    op.drop_constraint('ck_telemetry_batches_end_after_start', 'telemetry_batches', type_='check')
    op.drop_constraint(None, 'telemetry_batches', type_='foreignkey')
    op.create_foreign_key(op.f('telemetry_batches_shift_id_fkey'), 'telemetry_batches', 'shifts', ['shift_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_telemetry_batches_shift_start_timestamp', table_name='telemetry_batches')
    op.drop_constraint('ck_shifts_premium_non_negative', 'shifts', type_='check')
    op.drop_constraint('ck_shifts_end_after_start', 'shifts', type_='check')
    op.drop_constraint('ck_shifts_distance_non_negative', 'shifts', type_='check')
    op.drop_constraint(None, 'shifts', type_='foreignkey')
    op.create_foreign_key(op.f('shifts_rider_id_fkey'), 'shifts', 'users', ['rider_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('ck_risk_scores_window_end_after_start', 'risk_scores', type_='check')
    op.drop_constraint('ck_risk_scores_score_range', 'risk_scores', type_='check')
    op.drop_constraint('ck_risk_scores_overspeeding_non_negative', 'risk_scores', type_='check')
    op.drop_constraint('ck_risk_scores_hard_braking_non_negative', 'risk_scores', type_='check')
    op.drop_constraint('ck_risk_scores_hard_acceleration_non_negative', 'risk_scores', type_='check')
    op.drop_constraint(None, 'risk_scores', type_='foreignkey')
    op.drop_constraint(None, 'risk_scores', type_='foreignkey')
    op.create_foreign_key(op.f('risk_scores_shift_id_fkey'), 'risk_scores', 'shifts', ['shift_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('risk_scores_rider_id_fkey'), 'risk_scores', 'users', ['rider_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('ck_rider_profiles_safety_rating_range', 'rider_profiles', type_='check')
    op.drop_constraint('ck_payments_type_linkage', 'payments', type_='check')
    op.drop_constraint('ck_payments_amount_non_negative', 'payments', type_='check')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_rider_id_fkey'), 'payments', 'users', ['rider_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('ck_incidents_peak_g_force_non_negative', 'incidents', type_='check')
    op.drop_constraint('ck_incidents_confidence_score_range', 'incidents', type_='check')
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.create_foreign_key(op.f('incidents_rider_id_fkey'), 'incidents', 'users', ['rider_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('incidents_shift_id_fkey'), 'incidents', 'shifts', ['shift_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'incident_evidence', type_='foreignkey')
    op.drop_constraint(None, 'incident_evidence', type_='foreignkey')
    op.create_foreign_key(op.f('incident_evidence_claim_id_fkey'), 'incident_evidence', 'claims', ['claim_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('incident_evidence_incident_id_fkey'), 'incident_evidence', 'incidents', ['incident_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('ck_claims_claimed_amount_non_negative', 'claims', type_='check')
    op.drop_constraint('ck_claims_approved_amount_non_negative', 'claims', type_='check')
    op.drop_constraint(None, 'claims', type_='foreignkey')
    op.drop_constraint(None, 'claims', type_='foreignkey')
    op.drop_constraint(None, 'claims', type_='foreignkey')
    op.create_foreign_key(op.f('claims_incident_id_fkey'), 'claims', 'incidents', ['incident_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('claims_shift_id_fkey'), 'claims', 'shifts', ['shift_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('claims_rider_id_fkey'), 'claims', 'users', ['rider_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'audit_events', type_='foreignkey')
    op.drop_constraint(None, 'audit_events', type_='foreignkey')
    op.create_foreign_key(op.f('audit_events_performed_by_user_id_fkey'), 'audit_events', 'users', ['performed_by_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('audit_events_claim_id_fkey'), 'audit_events', 'claims', ['claim_id'], ['id'], ondelete='CASCADE')
    op.drop_column('audit_events', 'entity_id')
    op.drop_column('audit_events', 'entity_type')
    # ### end Alembic commands ###
