"""add premium quotes table

Revision ID: 3f6ad275c1e6
Revises: decb4ac175f7
Create Date: 2026-08-25 23:20:25.604532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f6ad275c1e6'
down_revision: Union[str, Sequence[str], None] = 'decb4ac175f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('premium_quotes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shift_id', sa.UUID(), nullable=False),
    sa.Column('rider_id', sa.UUID(), nullable=False),
    sa.Column('is_cold_start', sa.Boolean(), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('risk_band', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('scoring_method', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('pricing_mode', sa.String(length=30), nullable=False),
    sa.Column('base_premium', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('previous_premium', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('adjustment_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('final_premium', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rate_of_change_capped', sa.Boolean(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('base_premium >= 0', name='ck_premium_quotes_base_premium_non_negative'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_premium_quotes_confidence_range'),
    sa.CheckConstraint('final_premium >= 0', name='ck_premium_quotes_final_premium_non_negative'),
    sa.CheckConstraint('risk_score IS NULL OR (risk_score >= 0 AND risk_score <= 100)', name='ck_premium_quotes_risk_score_range'),
    sa.ForeignKeyConstraint(['rider_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_premium_quotes_rider_id'), 'premium_quotes', ['rider_id'], unique=False)
    op.create_index(op.f('ix_premium_quotes_shift_id'), 'premium_quotes', ['shift_id'], unique=True)
    # NOTE: autogenerate also detected the same pre-existing, unrelated
    # drift noted in e21bac4648a0_add_shift_behaviour_summaries_table.py —
    # users.is_phone_verified exists in the live DB but not in the
    # SQLAlchemy User model. Still out of this migration's scope
    # (premium_quotes only), so the drop was removed here too rather than
    # silently applied a second time.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_premium_quotes_shift_id'), table_name='premium_quotes')
    op.drop_index(op.f('ix_premium_quotes_rider_id'), table_name='premium_quotes')
    op.drop_table('premium_quotes')
    # ### end Alembic commands ###
