"""add_decision_and_verification_run_id_to_claims

Revision ID: 66f48f664e78
Revises: 4a2417d99f42
Create Date: 2026-08-26 19:58:03.948429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66f48f664e78'
down_revision: Union[str, Sequence[str], None] = '4a2417d99f42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('decided_by', sa.UUID(), nullable=True))
    op.add_column('claims', sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('claims', sa.Column('verification_run_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'claims', 'users', ['decided_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'claims', 'audit_events', ['verification_run_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'claims', type_='foreignkey')
    op.drop_constraint(None, 'claims', type_='foreignkey')
    op.drop_column('claims', 'verification_run_id')
    op.drop_column('claims', 'decided_at')
    op.drop_column('claims', 'decided_by')
    # ### end Alembic commands ###
