"""Add hospital features

Revision ID: 898d5c82409e
Revises: 7c45f2aef123
Create Date: 2026-08-26 00:01:18.107460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '898d5c82409e'
down_revision: Union[str, Sequence[str], None] = '7c45f2aef123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('locality', sa.String(length=100), nullable=False),
    sa.Column('contact_number', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospitals_locality'), 'hospitals', ['locality'], unique=False)
    op.create_table('claim_medical_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('file_reference', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_medical_reports_claim_id'), 'claim_medical_reports', ['claim_id'], unique=False)
    op.create_index(op.f('ix_claim_medical_reports_hospital_id'), 'claim_medical_reports', ['hospital_id'], unique=False)
    op.drop_index(op.f('ix_shift_behaviour_summaries_rider_id'), table_name='shift_behaviour_summaries')
    op.drop_index(op.f('ix_shift_behaviour_summaries_shift_id'), table_name='shift_behaviour_summaries')
    op.drop_table('shift_behaviour_summaries')
    op.drop_index(op.f('ix_premium_quotes_rider_id'), table_name='premium_quotes')
    op.drop_index(op.f('ix_premium_quotes_shift_id'), table_name='premium_quotes')
    op.drop_table('premium_quotes')
    op.drop_index(op.f('ix_rider_behaviour_profiles_rider_id'), table_name='rider_behaviour_profiles')
    op.drop_table('rider_behaviour_profiles')
    op.add_column('incidents', sa.Column('locality', sa.String(length=100), server_default="Unknown", nullable=False))
    op.create_index(op.f('ix_incidents_locality'), 'incidents', ['locality'], unique=False)
    op.add_column('users', sa.Column('hospital_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_hospital_id'), 'users', ['hospital_id'], unique=False)
    op.create_foreign_key(None, 'users', 'hospitals', ['hospital_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_hospital_id'), table_name='users')
    op.drop_column('users', 'hospital_id')
    op.drop_index(op.f('ix_incidents_locality'), table_name='incidents')
    op.drop_column('incidents', 'locality')
    op.create_table('rider_behaviour_profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rider_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('based_on_shift_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('based_on_valid_shift_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recent_avg_speed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('recent_max_speed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('recent_hard_braking_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('recent_hard_acceleration_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('recent_overspeeding_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('recent_sharp_turn_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('recent_max_g', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('recent_data_quality', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=False),
    sa.Column('medium_avg_speed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('medium_max_speed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('medium_hard_braking_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('medium_hard_acceleration_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('medium_overspeeding_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('medium_sharp_turn_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('medium_max_g', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('medium_data_quality', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=False),
    sa.Column('long_term_avg_speed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('long_term_max_speed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('long_term_hard_braking_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('long_term_hard_acceleration_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('long_term_overspeeding_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('long_term_sharp_turn_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('long_term_max_g', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('long_term_data_quality', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=False),
    sa.Column('hard_braking_rate_variance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('overspeeding_rate_variance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('speed_variability', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('behaviour_consistency_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('overall_behaviour_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('data_quality_score', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.CheckConstraint('based_on_shift_count >= 0', name=op.f('ck_rider_behaviour_profiles_shift_count_non_negative')),
    sa.CheckConstraint('based_on_valid_shift_count <= based_on_shift_count', name=op.f('ck_rider_behaviour_profiles_valid_le_total')),
    sa.CheckConstraint('based_on_valid_shift_count >= 0', name=op.f('ck_rider_behaviour_profiles_valid_shift_count_non_negative')),
    sa.CheckConstraint('behaviour_consistency_score >= 0::numeric AND behaviour_consistency_score <= 100::numeric', name=op.f('ck_rider_behaviour_profiles_consistency_score_range')),
    sa.CheckConstraint('confidence >= 0::numeric AND confidence <= 1::numeric', name=op.f('ck_rider_behaviour_profiles_confidence_range')),
    sa.CheckConstraint('data_quality_score >= 0::numeric AND data_quality_score <= 1::numeric', name=op.f('ck_rider_behaviour_profiles_data_quality_range')),
    sa.CheckConstraint('overall_behaviour_score >= 0::numeric AND overall_behaviour_score <= 100::numeric', name=op.f('ck_rider_behaviour_profiles_overall_score_range')),
    sa.ForeignKeyConstraint(['rider_id'], ['users.id'], name=op.f('rider_behaviour_profiles_rider_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('rider_behaviour_profiles_pkey'))
    )
    op.create_index(op.f('ix_rider_behaviour_profiles_rider_id'), 'rider_behaviour_profiles', ['rider_id'], unique=True)
    op.create_table('premium_quotes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('shift_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rider_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_cold_start', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('risk_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('risk_band', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=False),
    sa.Column('scoring_method', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('model_version', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('pricing_mode', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('base_premium', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('previous_premium', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('adjustment_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('final_premium', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('rate_of_change_capped', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('explanation', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.CheckConstraint('base_premium >= 0::numeric', name=op.f('ck_premium_quotes_base_premium_non_negative')),
    sa.CheckConstraint('confidence >= 0::numeric AND confidence <= 1::numeric', name=op.f('ck_premium_quotes_confidence_range')),
    sa.CheckConstraint('final_premium >= 0::numeric', name=op.f('ck_premium_quotes_final_premium_non_negative')),
    sa.CheckConstraint('risk_score IS NULL OR risk_score >= 0::numeric AND risk_score <= 100::numeric', name=op.f('ck_premium_quotes_risk_score_range')),
    sa.ForeignKeyConstraint(['rider_id'], ['users.id'], name=op.f('premium_quotes_rider_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('premium_quotes_shift_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('premium_quotes_pkey'))
    )
    op.create_index(op.f('ix_premium_quotes_shift_id'), 'premium_quotes', ['shift_id'], unique=True)
    op.create_index(op.f('ix_premium_quotes_rider_id'), 'premium_quotes', ['rider_id'], unique=False)
    op.create_table('shift_behaviour_summaries',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('shift_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rider_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('distance_km', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=False),
    sa.Column('sample_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('average_speed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('max_speed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('hard_braking_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hard_acceleration_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('overspeeding_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sharp_turn_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hard_braking_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('hard_acceleration_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('overspeeding_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('sharp_turn_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('max_g', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('accel_std', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('jerk_mean', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('sampling_density', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('data_quality_score', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=False),
    sa.Column('is_valid', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.CheckConstraint('data_quality_score >= 0::numeric AND data_quality_score <= 1::numeric', name=op.f('ck_shift_behaviour_summaries_quality_score_range')),
    sa.CheckConstraint('distance_km >= 0::numeric', name=op.f('ck_shift_behaviour_summaries_distance_non_negative')),
    sa.CheckConstraint('duration_seconds >= 0', name=op.f('ck_shift_behaviour_summaries_duration_non_negative')),
    sa.CheckConstraint('sample_count >= 0', name=op.f('ck_shift_behaviour_summaries_sample_count_non_negative')),
    sa.ForeignKeyConstraint(['rider_id'], ['users.id'], name=op.f('shift_behaviour_summaries_rider_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('shift_behaviour_summaries_shift_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('shift_behaviour_summaries_pkey'))
    )
    op.create_index(op.f('ix_shift_behaviour_summaries_shift_id'), 'shift_behaviour_summaries', ['shift_id'], unique=True)
    op.create_index(op.f('ix_shift_behaviour_summaries_rider_id'), 'shift_behaviour_summaries', ['rider_id'], unique=False)
    op.drop_index(op.f('ix_claim_medical_reports_hospital_id'), table_name='claim_medical_reports')
    op.drop_index(op.f('ix_claim_medical_reports_claim_id'), table_name='claim_medical_reports')
    op.drop_table('claim_medical_reports')
    op.drop_index(op.f('ix_hospitals_locality'), table_name='hospitals')
    op.drop_table('hospitals')
    # ### end Alembic commands ###
