"""add helmet verifications table

Revision ID: bd7ba87c5821
Revises: 3f6ad275c1e6
Create Date: 2026-08-26 01:44:18.335358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'bd7ba87c5821'
down_revision: Union[str, Sequence[str], None] = '3f6ad275c1e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('helmet_verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rider_id', sa.UUID(), nullable=False),
    sa.Column('shift_id', sa.UUID(), nullable=True),
    sa.Column('predicted_class', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('helmet_worn', sa.Boolean(), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_helmet_verifications_confidence_range'),
    sa.ForeignKeyConstraint(['rider_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_helmet_verifications_created_at'), 'helmet_verifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_helmet_verifications_rider_id'), 'helmet_verifications', ['rider_id'], unique=False)
    op.create_index(op.f('ix_helmet_verifications_shift_id'), 'helmet_verifications', ['shift_id'], unique=False)
    # NOTE: autogenerate also detected unrelated pre-existing drift —
    # hospitals/claim_medical_reports tables and incidents.locality/
    # users.hospital_id/users.is_phone_verified columns exist in the live
    # DB but not in the SQLAlchemy models. Same situation as the
    # is_phone_verified drift noted in the two earlier migrations in this
    # series; still out of this migration's scope (helmet_verifications
    # only), so none of those drops were applied here.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_helmet_verifications_shift_id'), table_name='helmet_verifications')
    op.drop_index(op.f('ix_helmet_verifications_rider_id'), table_name='helmet_verifications')
    op.drop_index(op.f('ix_helmet_verifications_created_at'), table_name='helmet_verifications')
    op.drop_table('helmet_verifications')
    # ### end Alembic commands ###
