"""add rider behaviour profiles table

Revision ID: decb4ac175f7
Revises: e21bac4648a0
Create Date: 2026-08-25 21:24:17.606993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'decb4ac175f7'
down_revision: Union[str, Sequence[str], None] = 'e21bac4648a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rider_behaviour_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rider_id', sa.UUID(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('based_on_shift_count', sa.Integer(), nullable=False),
    sa.Column('based_on_valid_shift_count', sa.Integer(), nullable=False),
    sa.Column('recent_avg_speed', sa.Float(), nullable=False),
    sa.Column('recent_max_speed', sa.Float(), nullable=False),
    sa.Column('recent_hard_braking_rate', sa.Float(), nullable=False),
    sa.Column('recent_hard_acceleration_rate', sa.Float(), nullable=False),
    sa.Column('recent_overspeeding_rate', sa.Float(), nullable=False),
    sa.Column('recent_sharp_turn_rate', sa.Float(), nullable=False),
    sa.Column('recent_max_g', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('recent_data_quality', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('medium_avg_speed', sa.Float(), nullable=False),
    sa.Column('medium_max_speed', sa.Float(), nullable=False),
    sa.Column('medium_hard_braking_rate', sa.Float(), nullable=False),
    sa.Column('medium_hard_acceleration_rate', sa.Float(), nullable=False),
    sa.Column('medium_overspeeding_rate', sa.Float(), nullable=False),
    sa.Column('medium_sharp_turn_rate', sa.Float(), nullable=False),
    sa.Column('medium_max_g', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('medium_data_quality', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('long_term_avg_speed', sa.Float(), nullable=False),
    sa.Column('long_term_max_speed', sa.Float(), nullable=False),
    sa.Column('long_term_hard_braking_rate', sa.Float(), nullable=False),
    sa.Column('long_term_hard_acceleration_rate', sa.Float(), nullable=False),
    sa.Column('long_term_overspeeding_rate', sa.Float(), nullable=False),
    sa.Column('long_term_sharp_turn_rate', sa.Float(), nullable=False),
    sa.Column('long_term_max_g', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('long_term_data_quality', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('hard_braking_rate_variance', sa.Float(), nullable=False),
    sa.Column('overspeeding_rate_variance', sa.Float(), nullable=False),
    sa.Column('speed_variability', sa.Float(), nullable=False),
    sa.Column('behaviour_consistency_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('overall_behaviour_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('data_quality_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('based_on_shift_count >= 0', name='ck_rider_behaviour_profiles_shift_count_non_negative'),
    sa.CheckConstraint('based_on_valid_shift_count <= based_on_shift_count', name='ck_rider_behaviour_profiles_valid_le_total'),
    sa.CheckConstraint('based_on_valid_shift_count >= 0', name='ck_rider_behaviour_profiles_valid_shift_count_non_negative'),
    sa.CheckConstraint('behaviour_consistency_score >= 0 AND behaviour_consistency_score <= 100', name='ck_rider_behaviour_profiles_consistency_score_range'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_rider_behaviour_profiles_confidence_range'),
    sa.CheckConstraint('data_quality_score >= 0 AND data_quality_score <= 1', name='ck_rider_behaviour_profiles_data_quality_range'),
    sa.CheckConstraint('overall_behaviour_score >= 0 AND overall_behaviour_score <= 100', name='ck_rider_behaviour_profiles_overall_score_range'),
    sa.ForeignKeyConstraint(['rider_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rider_behaviour_profiles_rider_id'), 'rider_behaviour_profiles', ['rider_id'], unique=True)
    # NOTE: same pre-existing, unrelated users.is_phone_verified drift
    # autogenerate detected in e21bac4648a0 (Phase 1's migration) — removed
    # from upgrade()/downgrade() here for the same reason, not this
    # migration's concern.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rider_behaviour_profiles_rider_id'), table_name='rider_behaviour_profiles')
    op.drop_table('rider_behaviour_profiles')
    # ### end Alembic commands ###
