"""add shift behaviour summaries table

Revision ID: e21bac4648a0
Revises: 7c45f2aef123
Create Date: 2026-08-25 21:01:32.613971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e21bac4648a0'
down_revision: Union[str, Sequence[str], None] = '7c45f2aef123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_behaviour_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shift_id', sa.UUID(), nullable=False),
    sa.Column('rider_id', sa.UUID(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('distance_km', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('average_speed', sa.Float(), nullable=False),
    sa.Column('max_speed', sa.Float(), nullable=False),
    sa.Column('hard_braking_count', sa.Integer(), nullable=False),
    sa.Column('hard_acceleration_count', sa.Integer(), nullable=False),
    sa.Column('overspeeding_count', sa.Integer(), nullable=False),
    sa.Column('sharp_turn_count', sa.Integer(), nullable=False),
    sa.Column('hard_braking_rate', sa.Float(), nullable=False),
    sa.Column('hard_acceleration_rate', sa.Float(), nullable=False),
    sa.Column('overspeeding_rate', sa.Float(), nullable=False),
    sa.Column('sharp_turn_rate', sa.Float(), nullable=False),
    sa.Column('max_g', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('accel_std', sa.Float(), nullable=False),
    sa.Column('jerk_mean', sa.Float(), nullable=False),
    sa.Column('sampling_density', sa.Float(), nullable=False),
    sa.Column('data_quality_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('data_quality_score >= 0 AND data_quality_score <= 1', name='ck_shift_behaviour_summaries_quality_score_range'),
    sa.CheckConstraint('distance_km >= 0', name='ck_shift_behaviour_summaries_distance_non_negative'),
    sa.CheckConstraint('duration_seconds >= 0', name='ck_shift_behaviour_summaries_duration_non_negative'),
    sa.CheckConstraint('sample_count >= 0', name='ck_shift_behaviour_summaries_sample_count_non_negative'),
    sa.ForeignKeyConstraint(['rider_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_behaviour_summaries_rider_id'), 'shift_behaviour_summaries', ['rider_id'], unique=False)
    op.create_index(op.f('ix_shift_behaviour_summaries_shift_id'), 'shift_behaviour_summaries', ['shift_id'], unique=True)
    # NOTE: autogenerate also detected a pre-existing, unrelated drift —
    # users.is_phone_verified exists in the live DB but not in the
    # SQLAlchemy User model — and proposed dropping that column here. That
    # drift predates this migration and this phase's scope is strictly
    # ShiftBehaviourSummary, so the drop was deliberately removed from both
    # upgrade() and downgrade() rather than silently applied. Flagged in
    # the Phase 1 report as a separate, pre-existing issue to resolve on
    # its own.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shift_behaviour_summaries_shift_id'), table_name='shift_behaviour_summaries')
    op.drop_index(op.f('ix_shift_behaviour_summaries_rider_id'), table_name='shift_behaviour_summaries')
    op.drop_table('shift_behaviour_summaries')
    # ### end Alembic commands ###
